language: go
go:
  - '1.10'
  - '1.11'
  - tip

os:
  - linux

sudo: false

script:
  - make test
  - make int_test

before_install:
  - sudo apt-get install -y expect

addons:
  apt:
    update: true

matrix:
  allow_failures:
  - go: tip
